### ISSUE TITLE
小米9安装证书成功，但是抓包仍是加密

### ISSUE THREAD

**Issue by sunseekers** [crifan/app_capture_package_tool_charles#1]
你好想问一下，按照你的步骤，用户凭据和信任的凭据那里都有显示安装成功证书。可是抓包的时候仍然是加密的接口。
用ios进行抓包没有任何问题
安卓进行抓包，每次都失败了

**Comment by crifan** [comment]
小米9的Android版本应该都是9，10左右了，早就超过7.0了
所以估计是系统不信任用户证书
所以你自己参考：[破解https的SSL Pinning · app抓包利器：Charles](https://book.crifan.com/books/app_capture_package_tool_charles/website/how_capture_app/complex_https/https_ssl_pinning/)去用（比如：`Xposed框架`+`JustTrustMe `）破解才可以

**Comment by sunseekers** [comment]
看看了除了换手机没有别的，方法了
